version: "3"
services:
  db:
    image: mariadb:10.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "password"
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    networks:
    - english-learner-network

  web:
    build:
      context: ./english-learner-api
      dockerfile: ./Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./english-learner-api:/app:cached
      - bundle-volume:/usr/local/bundle
    ports:
      - 3000:3000
    networks:
      - english-learner-network
    depends_on:
      - db
    tty: true
    stdin_open: true

  front:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - english-learner-network
    tty: true
    command: sh -c 'npm start'

volumes:
  bundle-volume:
  db-data:
    
networks:
  english-learner-network:
    external: true
